### PR TITLE
Allow override policy and roles names

### PR DESCRIPTION
**Pull request by Th0masL**
I wanted to be able to enforce specific names for most of the resources, so here is a PR for that, plus some other small fixes:

- add allow override policy name
- add allow override role name
- add allow override terraform's user policy name
- add tags on some more resources

## Tests

I was able to test my changes by using the module directly from this branch, see below.

```
module "remote_state" {
  #source = "nozaq/remote-state-s3-backend/aws"
  #version = "1.3.2"
  source = "git::https://github.com/Th0masL/terraform-aws-remote-state-s3-backend.git?ref=custom-policy-name"

  # Enforce static named resources
  dynamodb_table_name                = "tf-remote-state-lock-${var.env}"
  override_s3_bucket_name            = true
  s3_bucket_name                     = "tf-remote-state-${var.company_name}-${var.env}"
  s3_bucket_name_replica             = "tf-remote-state-replica-${var.company_name}-${var.env}"
  override_iam_policy_name           = true
  iam_policy_name                    = "tf-remote-state-policy-${var.env}"
  override_iam_role_name             = true
  iam_role_name                      = "tf-remote-state-role-${var.env}"
  override_terraform_iam_policy_name = true
  terraform_iam_policy_name          = "terraform-policy-${var.env}"

  providers = {
    aws         = aws
    aws.replica = aws.replica
  }
}
```

```
$ terraform init
Initializing modules...
Downloading git::https://github.com/Th0masL/terraform-aws-remote-state-s3-backend.git?ref=custom-policy-name for remote_state...
- remote_state in .terraform/modules/remote_state

$ terraform validate
Success! The configuration is valid.

$ terraform plan
Plan: 21 to add, 0 to change, 21 to destroy.

$ terraform apply
Apply complete! Resources: 21 added, 0 changed, 21 destroyed.

Outputs:

dynamodb_table_name = "tf-remote-state-lock-dev"
kms_key_alias = "alias/tf-remote-state-key"
kms_key_id = "eff73f35-e888-43d2-b477-XXXXXXXX"
replica_bucket_name = "tf-remote-state-replica-XXXXXXXX-dev"
state_bucket_name = "tf-remote-state-XXXXXXXX-dev"
terraform_iam_policy_name = "terraform-policy-dev"
```

### CODE REVIEW

**Comment by Th0masL** [comment]
Hi @nozaq !
Do you need me to change something around this PR ? Or can we get it merged ?
Thanks !

**Comment by nozaq** [comment]
Sorry for being late, LGTM!

**Comment by Th0masL** [comment]
Sorry to ask you again, but do you know when you will be releasing a new version that includes this improvement ?

**Comment by WillGreen** [comment]
Is there any news on this getting released?
We can't use your otherwise promising looking module without it. Thanks.

**Comment by nozaq** [comment]
@Th0masL @WillGreen Sorry, automatic release generation somehow didn't work. This change is included in v1.4.0 now, thanks for your patience!

**Pull request merged**
