### PR TITLE
enabled server side encryption in dynamo db table creation

### LINKED ISSUE #70: Enable Server Side Encryption in Dynamo DB Table Creation
As a best practice, please enable server side encryption in dynamo db table creation

dynamo.tf

server_side_encryption {
enabled = var.server_side_encryption_enabled
kms_key_arn = var.server_side_encryption_kms_key_arn
}

### PR DESCRIPTION
**Pull request by Aravind36064**
enabled server side encryption in dynamo db table creation 

Fix #70

### CODE REVIEW

**Review by nozaq — CHANGES_REQUESTED** [review]
@Aravind36064 
Thank you for your contribution! The change itself looks good to me.
Just one small request, could you exclude CHANGELOG.md change from the PR? This would be automatically generated based on the commit message.

**Comment by Aravind36064** [comment]
> @Aravind36064 Thank you for your contribution! The change itself looks good to me. Just one small request, could you exclude CHANGELOG.md change from the PR? This would be automatically generated based on the commit message.

@nozaq  The changelog entry is removed

**Review by nozaq — APPROVED** [review]
Thanks for the quick update, LGTM!

**Comment by Aravind36064** [comment]
@nozaq can you update new version of this module as well

**Comment by nozaq** [comment]
@Aravind36064 Just published [v1.1.0](https://github.com/nozaq/terraform-aws-remote-state-s3-backend/releases/tag/v1.1.0)! 
Note: I made [a small fix](https://github.com/nozaq/terraform-aws-remote-state-s3-backend/commit/c1c9262064c25d9437a97e7ea8793a4250ee6708) for variable name consistency.

**Pull request merged**
